[tool.poetry]
name = "squidalytics-ink"
version = "0.1.0"
description = "Squidalytics Main Website built in Django"
authors = ["Cesar E Garza <cesar@cegarza.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
packages = [{include = "squidalytics"}]

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.2"
python-dotenv = "^1.0.0"
wagtail = "^5.0"
psycopg2-binary = "^2.9.6"
wagtailcodeblock = "^1.29.0.0"
wagtail-markdown = "^0.11.0"
wagtailmedia = "^0.14.2"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 80
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 80
